### ISSUE TITLE
Getting 403 when I visit /studio

### ISSUE THREAD

**Issue by projectrebel** [cnvs/studio#11] opened 2020-03-17 22:44 UTC
I installed this on a fresh laravel project which only has canvas installed and configured. I created one post and then tried to install this and view my post.  If I visit the `/studio` url directly, I will get a 403 error.  If I try sub urls, I am able to view those pages (such as `/studio/tags` and `/studio/topics`). Once I'm one a sub page, then I can click the home button and view `/studio` to see the overview but I will get a 403 again if I refresh the page.

**Comment by austintoddj** [comment] 2020-03-17 23:55
Are there any errors in the console that you can see?

**Comment by projectrebel** [comment] 2020-03-18 10:58
Just the 403 error

> Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by austintoddj** [comment] 2020-03-18 15:04
Not able to reproduce it on a fresh install. You have authentication and the db set up for the base Laravel app?

**Comment by projectrebel** [comment] 2020-03-19 14:41
That's correct. I'll give it another try on a fresh install

**Comment by projectrebel** [comment] 2020-03-19 15:48
I tried a fresh install using `laravel new project --auth` and installing the auth package separately but I get the same issue in both cases.  I am running XAMPP 7.2, Apache 2.4.39, OpenSSL 1.1.1c, PHP 7.2.20 on Windows 10 Home.

**Comment by armancodes** [comment] 2020-03-21 21:58
I have the same issue with the `/studio` route.
When I try to reach `/studio` in my application l get this error:
![image](https://user-images.githubusercontent.com/22839699/77237265-2b379580-6be4-11ea-9cc8-3a5df5c3b6c8.png)
But when I enter `studio/posts` it redirects me to `studio/`, and it shows the posts.
I tried reaching `studio/` but it didn't work.

**Comment by armancodes** [comment] 2020-03-21 22:08
I tried to change the `studio` default URL in the `studio.php` config file to something else.
It worked.
I think there should be a problem with the prefix `/studio`.

**Comment by austintoddj** [comment] 2020-03-22 10:56
If you run the `route:list` Artisan command, what do you get?

**Comment by armancodes** [comment] 2020-03-22 11:03
This is what I get:
![image](https://user-images.githubusercontent.com/22839699/77247832-6a9ccb00-6c52-11ea-8b0a-843f1ac9b15b.png)

**Comment by austintoddj** [comment] 2020-03-22 11:10
When you look at the Console errors, is the 403 coming from the `/studio` route or the `/studio/api/posts` route?

**Comment by armancodes** [comment] 2020-03-22 11:13
I'm getting 404 coming from `/studio`:
![image](https://user-images.githubusercontent.com/22839699/77248019-e5b2b100-6c53-11ea-853a-9cbb2e202f00.png)

**Comment by armancodes** [comment] 2020-03-22 11:15
And here is the console error:
![image](https://user-images.githubusercontent.com/22839699/77248055-21e61180-6c54-11ea-9502-fe4d9fed9b28.png)

**Comment by austintoddj** [comment] 2020-03-22 11:20
I'll have to dig into this a little more since I'm not able to replicate this on my end. Something about the way the routes are being handled doesn't look right.

If you find anything out feel free to update here or submit a PR!

**Comment by Mint-developer** [comment] 2020-03-23 09:50
@armancodes yes you are right! I changed STUDIO_PATH_NAME to "mystudio". It worked.

**Comment by austintoddj** [comment] 2020-04-02 15:58
@armancodes Is this resolved then?

**Comment by armancodes** [comment] 2020-04-02 18:53
@austintoddj No, when I try to access it with `studio` pathname, it doesn't work, but if I change `STUDIO_PATH_NAME ` to something else, it will be resolved.

**Comment by robertgarrigos** [comment] 2020-04-25 03:05
Same happens here. 'studio' gives a 403 error. Anything else works, even a blank path.

**Comment by austintoddj** [comment] 2020-04-25 19:41
@robertgarrigos Is there anything on your end that might point to why this is happening? Still not able to replicate it on my end, even though numerous people have run into this.

**Comment by albertoelias123** [comment] 2020-04-25 19:42
I had the same problem, changing the "STUDIO_PATH_NAME" to 'blog' or something else works perfectly.

Note: The '/ studio' route keeps returning ERR 403

**Comment by robertgarrigos** [comment] 2020-04-26 02:58
@austintoddj I see what's happening, although I don't know why it is doing it:

I'm using Lando (don't if this is determinant) but this is related to Apache, not to the Laravel routes, which get well-defined as you can see with `artisan route:list`. Whenever you set the path to something different to `studio`, Apache serves `/public/index.php`. However, when it's set to `studio`, it tries to serve `/public/studio/index.php`, which it doesn't exist (this is a directory created by studio during install, I guess, with css and js subdirectories). The problem disappears when you change the name of that directory `public/studio` to something else. Then, setting path to `studio` works as expected (of course, then you have css and js files missing, but not a 403 error). In fact, I set the path to `blog`and then changed that `/public/studio`directory to `/public/blog`and got the 403 error again. What I don't see is why it's doing this. Hope this helps.

**Comment by austintoddj** [comment] 2020-04-26 03:14
That's really helpful insight @robertgarrigos, thank you.

@albertoelias123 @armancodes @Mint-developer Are you using something similar to serve your sites with?

**Comment by robertgarrigos** [comment] 2020-04-26 10:45
@austintoddj I just tried with my blog on production, a normal ubuntu 18.04 with apache and php7.4 and it dos the same, so not just with Lando in local :-(

**Comment by armancodes** [comment] 2020-04-26 10:56
@austintoddj I used Xampp on local and LEMP stack for production on ubuntu 18.04.
PHP 7.4

**Comment by austintoddj** [comment] 2020-04-26 19:40
Ok thanks for the details. Still working on a resolution to this.

**Comment by BuyOwnEx** [comment] 2020-04-26 20:04
The same issue with local Apache + PHP 7.2

**Comment by davidgrzyb** [comment] 2020-05-10 17:40
I've replicated this issue on a Windows 10 machine with XAMPP, when attempting to replicate on OSX with Valet the routing worked as intended. This makes sense because Valet uses NGINX.

I agree with @robertgarrigos, Canvas assets are in the `public/vendor/canvas` directory, whereas Studio's assets are in `public/studio`. When Apache is using the .htaccess to rewrite URLs, it finds the Studio directory under public and attempts to find a `DirectoryIndex`. The 403 is probably Apache trying to directory-list `/studio` without the permissions to do so.

The exact error is this:
```
[Sun May 10 11:26:49.833695 2020] [autoindex:error] [pid 20884:tid 1928] [client ::1:49693] AH01276: Cannot serve directory [PATH]/laravel/public/studio/: No matching DirectoryIndex (index.php,index.pl,index.cgi,index.asp,index.shtml,index.html,index.htm,default.php,default.pl,default.cgi,default.asp,default.shtml,default.html,default.htm,home.php,home.pl,home.cgi,home.asp,home.shtml,home.html,home.htm) found, and server-generated directory index forbidden by Options directive
```

### Temporary solution
- Move `/public/studio` to `/public/vendor`
- Edit your webpack.mix.js to look like below
```
mix.js('resources/js/studio/app.js', 'public/vendor/studio/js')
    .sass('resources/sass/studio/app.scss', 'public/vendor/studio/css');
```
- Edit CSS and JS tags in `resources/views/studio/app.css` to point to `vendor/studio/` 
```
<link href="{{ mix('vendor/studio/css/app.css') }}" rel="stylesheet">
<script src="{{ asset('vendor/studio/js/app.js') }}" defer></script>
```
- Run `npm run dev`

### Permanent solution
Move the `/studio` directory to the `/public/vendor` directory. @austintoddj what do you think? Can have a PR made for this if you are onboard with these changes.

**Comment by austintoddj** [comment] 2020-05-10 17:51
Really good find @davidgrzyb, super helpful. Yeah, go ahead and submit a PR with the changes and I’ll take a look.

**Comment by austintoddj** [comment] 2020-05-15 16:31
Fixed in https://github.com/cnvs/studio/pull/13

**Closed by austintoddj** 2020-05-15 16:31 UTC
